elef_milim/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('questions.urls')),
]

questions/urls.py
from django.urls import path

from .views import LessonDetailView, LessonListView

urlpatterns = [
    path('', LessonListView.as_view(), name='lesson-list'),
    path('<slug:slug>/', LessonDetailView.as_view(), name='lesson-detail'),
]

questions/models.py
from django.db import models


class Lesson(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    lesson_link = models.URLField(blank=True, null=True)
    audio_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return self.slug


class Question(models.Model):
    GENDER_CHOICES = (
        ('m', 'male'),
        ('f', 'female'),
    )
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    text = models.CharField(max_length=256)
    correct_answers = models.CharField(max_length=250, help_text="List separated by comma")
    css_class = models.CharField(max_length=250, blank=True, null=True)
    position = models.CharField(max_length=250, blank=True, null=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=1, blank=True, null=True)

    def __str__(self):
        return self.text

    @property
    def correct_answers_list(self):
        return self.correct_answers.split(',')

questions/views.py
from django.utils import timezone
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView


from .models import Question, Lesson

class LessonListView(ListView):
    model = Lesson

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class LessonDetailView(DetailView):
    model = Lesson

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

questions/templates/questions/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    <title>Elef milim</title>
</head>
<body>
<nav class="navbar navbar-light">
  <a class="navbar-brand" href="/">
          אלף מילים
  </a>
</nav>
<div class="container">
  <div class="row">
     <main role="main" class="col-12 bd-content">
        {% block content %}
        {% endblock %}
     </main>
  </div>
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block  js %}
    {% endblock %}
</body>

</html>


questions/templates/questions/lesson_detail.html
{% extends 'questions/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm">
   <h1>
       {{ object }}
       <button id="help" class="btn btn-default pull-right text-danger h2">
           <i class="fa fa-life-ring"></i>
       </button>
   </h1>
  <div class="alert alert-success hide" id="success">
     <strong>Complimenti!</strong> Hai riposto a tutte le domande.
  </div>
  <div class="alert alert-danger hide" id="result">
  </div>
    {% comment %}
    <audio controls width="100%">
    <source src="{{ object.audio_link }}" type="audio/mpeg">
    Your browser does not support the audio element.
    </audio>

    <iframe src="{{ object.lesson_link}}" height="900px" width="100%"></iframe>
    {% endcomment %}

    <form class="form-inline">
        {% for question in object.question_set.all %}
        <div class="form-group col-lg-4 col-sm-12 p-3">
            <label class="col-6" for="q{{ question.pk}}">
                {{question.text }}
                &nbsp;
                <a href="https://forvo.com/search/{{question.text}}/he/" target="_blank" tabindex="-1">
                    <i class="fa fa-volume-up"></i>
                </a>
            </label>
            <input class="{% if question.gender %}col-3{% else %}col-6{%endif %} form-control question" id="q{{ question.pk }}" >
            {% if question.gender %}
                <div class="col-3 custom-control custom-radio">
                    <label>
                    <input type="radio" name="gender-q{{ question.pk}}" value="m">
                        &nbsp;
                    <i class="fa fa-male"></i>
                    </label>
                    <label>
                    <input type="radio" name="gender-q{{ question.pk }}" value="f">
                        &nbsp;
                    <i class="fa fa-female"></i>
                    </label>
                </div>
            {% endif %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button id="submit" class="btn btn-primary">Controlla</button>
        </div>
    </form>
</div>

{% endblock %}

{% block js %}
<script>
dict = {
    {% for question in object.question_set.all %}
    'q{{ question.pk }}': {
            'correct': [{% for ca in question.correct_answers_list %}"{{ ca }}"{% if not forloop.last %}, {% endif %}{% endfor %}],
            'gender': '{{ question.gender }}'
        },
    {% endfor %}
}

var questions_count = {{ object.question_set.all|length }};
</script>
<script src="{% static 'js/lesson.js' %}"></script>
{% endblock %}

questions/templates/questions/lesson_list.html
{% extends 'questions/base.html' %}
{% block content %}
<div class="row">
    <ul class="list-group navbar-nav ">
        {% for lesson in object_list %}
	<li class="nav-item"> 
           <a class="nav-link" href="{{ lesson.get_absolute_url }}"> {{ lesson }}</a>
        {% endfor %}
    </ul>
</div>
{% endblock %}